apiVersion: v1
kind: Service
metadata:
  labels:
    app: storefront
  name: storefront
spec:
  ports:
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 4200
  selector:
    app: storefront
  type: LoadBalancer
